# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: EthosProtocol
description: Ethos protocol indexer
#Global contract definitions that must contain all definitions except
#addresses. Now you can share a single handler/abi/event definitions
#for contracts across multiple chains
contracts:
  - name: ModuleRegistry
    abi_file_path: ./abis/ModuleRegistry.sol/ModuleRegistry.json
    handler: ./src/ModuleRegistryHandlers.ts
    events:
      - event: ModuleRegistered
      - event: ModuleRemoved
  - name: MissionFactory
    abi_file_path: ./abis/MissionFactory.sol/MissionFactory.json
    handler: ./src/MissionFactoryHandlers.ts
    events:
      - event: MissionCreated
      - event: AllowedTokenUpdated
networks:
  - id: 31337 # Anvil local deployment
    start_block: 0
    rpc_config:
      url: http://127.0.0.1:8545
    contracts:
      - name: ModuleRegistry
        address: 0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512
      - name: MissionFactory
        address: 0x610178dA211FEF7D417bC0e6FeD39F05609AD788
# Rollback on reorg mode currently incurs a performance hit on historical sync
# while developing an indexer we recommend setting this to false
rollback_on_reorg: false
